Prefix: "&cAdventskalender &8| &7"
RewardMSG: "&aDu erhälst deine Belohnung aus dem %day%. Türchen"
AlreadyEarned: "&cDu hast das heutige Türchen bereits geöffnet"
NotCurrentDay: "&cDieser Tag ist heute nicht"
Reward:
  1: "give %player% minecraft:diamond 1"
  2: "give %player% minecraft:diamond 1"
  3: "give %player% minecraft:diamond 1"
  4: "give %player% minecraft:diamond 1"
  5: "give %player% minecraft:diamond 1"
  6: "give %player% minecraft:diamond 1"
  7: "give %player% minecraft:diamond 1"
  8: "give %player% minecraft:diamond 1"
  9: "give %player% minecraft:diamond 1"
  10: "give %player% minecraft:diamond 1"
  12: "give %player% minecraft:diamond 1"
  13: "give %player% minecraft:diamond 1"
  14: "give %player% minecraft:diamond 1"
  15: "give %player% minecraft:diamond 1"
  16: "give %player% minecraft:diamond 1"
  17: "give %player% minecraft:diamond 1"
  18: "give %player% minecraft:diamond 1"
  19: "give %player% minecraft:diamond 1"
  20: "give %player% minecraft:diamond 1"
  21: "give %player% minecraft:diamond 1"
  22: "give %player% minecraft:diamond 1"
  23: "give %player% minecraft:diamond 1"
  24:
    - "give %player% minecraft:diamond 1"
    - "give %player% minecraft:emerald 1"